[package]
name = "hcpl_io"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/THE-nio/hcpl"
license = "MIT"

[dependencies]
hcpl_integer = { path = "../hcpl_integer" }
hcpl_proc_macro = { path = "../hcpl_proc_macro" }

[features]
derive = []